/**
 * Free fonts library — a hand-picked list of strong, free fonts (all SIL Open Font License),
 * Hebrew first. Weights, subsets and licence were read from the @fontsource packages on npm;
 * the descriptions are mine.
 */
export type FontCat = "sans" | "serif" | "display" | "hand";
export interface CatalogFont {
  /** fontsource / npm id */
  id: string;
  /** Google Fonts family name */
  family: string;
  cat: FontCat;
  /** best for headings, body text, or both */
  use: "כותרות" | "טקסט" | "שניהם";
  hebrew: boolean;
  weights: number[];
  italic: boolean;
  license: string;
  /** what's special about it */
  special: string;
  designer: string;
}

export const FONT_CATS: { v: FontCat; l: string }[] = [
  { v: "sans", l: "רגיל (סנס)" },
  { v: "serif", l: "סריף" },
  { v: "display", l: "כותרות ותצוגה" },
  { v: "hand", l: "כתב יד" },
];

export const CATALOG: CatalogFont[] = [
  {
    id: "heebo",
    family: "Heebo",
    cat: "sans",
    use: "שניהם",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special:
      "הפונט העברי הכי נפוץ באתרים. נקי, מודרני וקריא מאוד, עם 9 משקלים מדק מאוד ועד שחור. בחירה בטוחה כמעט לכל עסק, ועובד מצוין גם בטלפון.",
    designer: "עודד עזר (העברית), על בסיס Roboto",
  },
  {
    id: "rubik",
    family: "Rubik",
    cat: "sans",
    use: "שניהם",
    hebrew: true,
    weights: [300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special:
      "פינות מעוגלות קלות שנותנות תחושה חמה ונגישה. עברית ואנגלית מתואמות באופן מושלם, ויש גם נטוי. מתאים למותגים צעירים, אפליקציות ועסקים שרוצים להיראות ידידותיים.",
    designer: "Hubert & Fischer",
  },
  {
    id: "assistant",
    family: "Assistant",
    cat: "sans",
    use: "טקסט",
    hebrew: true,
    weights: [200, 300, 400, 500, 600, 700, 800],
    italic: false,
    license: "OFL-1.1",
    special:
      "פונט טקסט נוח מאוד לקריאה ארוכה, עם 7 משקלים. נראה מקצועי ושקט, מצוין לגוף טקסט, טפסים וממשקים.",
    designer: "Ben Nathan (העברית), על בסיס Source Sans",
  },
  {
    id: "varela-round",
    family: "Varela Round",
    cat: "sans",
    use: "שניהם",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special:
      "עגול לגמרי, רך וידידותי. מתאים לילדים, חינוך, בריאות ומותגים נעימים. יש לו משקל אחד בלבד.",
    designer: "",
  },
  {
    id: "secular-one",
    family: "Secular One",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special:
      "כותרות עבות עם הרבה אופי ונוכחות. מושך את העין בפתיח של אתר ובבאנרים. משקל אחד, לכן מתאים לכותרות ולא לטקסט.",
    designer: "מיכל סהר",
  },
  {
    id: "frank-ruhl-libre",
    family: "Frank Ruhl Libre",
    cat: "serif",
    use: "שניהם",
    hebrew: true,
    weights: [300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special:
      "סריף עברי קלאסי בהשראת פרנק-רוהל, האות של העיתונים והספרים. משדר אמינות ומסורת. מעולה לעורכי דין, מוסדות, תוכן תורני וכתבות.",
    designer: "יאנק יונטף",
  },
  {
    id: "david-libre",
    family: "David Libre",
    cat: "serif",
    use: "טקסט",
    hebrew: true,
    weights: [400, 500, 700],
    italic: false,
    license: "OFL-1.1",
    special:
      "גרסה חופשית של האות דוד המוכרת. רשמי, מכובד ונקרא היטב, מתאים למסמכים, מוסדות ותוכן רציני.",
    designer: "",
  },
  {
    id: "alef",
    family: "Alef",
    cat: "sans",
    use: "טקסט",
    hebrew: true,
    weights: [400, 700],
    italic: false,
    license: "OFL-1.1",
    special: "סנס עברי פשוט, נקי ושימושי עם שני משקלים. מתאים לטקסט רגיל באתרים פשוטים.",
    designer: "",
  },
  {
    id: "suez-one",
    family: "Suez One",
    cat: "serif",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "סריף כבד ובולט לכותרות, עם נוכחות חזקה ומעט סגנון קלאסי. נראה מצוין בגדלים גדולים.",
    designer: "מיכל סהר",
  },
  {
    id: "amatic-sc",
    family: "Amatic SC",
    cat: "hand",
    use: "כותרות",
    hebrew: true,
    weights: [400, 700],
    italic: false,
    license: "OFL-1.1",
    special: "כתב יד צר בטוש, משחקי ומזמין. מתאים לבתי קפה, אירועים ומוצרי יד, רק לכותרות קצרות.",
    designer: "Vernon Adams",
  },
  {
    id: "karantina",
    family: "Karantina",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [300, 400, 700],
    italic: false,
    license: "OFL-1.1",
    special: "צר וגבוה מאוד, נכנס הרבה טקסט בשורה אחת. מושלם לכותרות ענק, פוסטרים ומבצעים.",
    designer: "",
  },
  {
    id: "bellefair",
    family: "Bellefair",
    cat: "serif",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "סריף אלגנטי ועדין עם ניגודיות עדינה. מתאים לאופנה, תכשיטים, אירועים ומותגי יוקרה.",
    designer: "Nick Shinn ולירון לביא טורקניץ'",
  },
  {
    id: "noto-sans-hebrew",
    family: "Noto Sans Hebrew",
    cat: "sans",
    use: "שניהם",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special: "פונט של גוגל: ניטרלי, שלם ואמין, עם 9 משקלים ותמיכה מלאה בניקוד. עובד טוב בכל מקום.",
    designer: "Google",
  },
  {
    id: "noto-serif-hebrew",
    family: "Noto Serif Hebrew",
    cat: "serif",
    use: "טקסט",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special:
      "סריף ניטרלי ונקרא לטקסטים ארוכים, עם 9 משקלים וניקוד מלא. מתאים לספרות, מאמרים ותוכן תורני.",
    designer: "Google",
  },
  {
    id: "noto-rashi-hebrew",
    family: "Noto Rashi Hebrew",
    cat: "serif",
    use: "כותרות",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special: 'כתב רש"י המסורתי בגרסה מודרנית ושלמה. מתאים לתוכן תורני, ציטוטים והדגשות.',
    designer: "Google",
  },
  {
    id: "ibm-plex-sans-hebrew",
    family: "IBM Plex Sans Hebrew",
    cat: "sans",
    use: "שניהם",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700],
    italic: false,
    license: "OFL-1.1",
    special: "טכנולוגי, מדויק ומקצועי. מתאים לחברות טק, SaaS, הנדסה וייעוץ.",
    designer: "IBM",
  },
  {
    id: "open-sans",
    family: "Open Sans",
    cat: "sans",
    use: "טקסט",
    hebrew: true,
    weights: [300, 400, 500, 600, 700, 800],
    italic: true,
    license: "OFL-1.1",
    special: "קריא מאוד גם בגדלים קטנים, עם עברית ונטוי. בחירה בטוחה וניטרלית לגוף טקסט.",
    designer: "Steve Matteson",
  },
  {
    id: "miriam-libre",
    family: "Miriam Libre",
    cat: "sans",
    use: "טקסט",
    hebrew: true,
    weights: [400, 500, 600, 700],
    italic: false,
    license: "OFL-1.1",
    special: "גרסה חופשית ומרועננת של מרים המוכרת. נקי ומוכר לעין הישראלית.",
    designer: "",
  },
  {
    id: "tinos",
    family: "Tinos",
    cat: "serif",
    use: "טקסט",
    hebrew: true,
    weights: [400, 700],
    italic: true,
    license: "OFL-1.1",
    special: "תואם במידות ל-Times New Roman, עם עברית. מתאים למסמכים ולטקסט רשמי.",
    designer: "Steve Matteson",
  },
  {
    id: "arimo",
    family: "Arimo",
    cat: "sans",
    use: "טקסט",
    hebrew: true,
    weights: [400, 500, 600, 700],
    italic: true,
    license: "OFL-1.1",
    special: "תואם במידות ל-Arial, עם עברית. ניטרלי ובטוח לטקסט.",
    designer: "Steve Matteson",
  },
  {
    id: "fredoka",
    family: "Fredoka",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [300, 400, 500, 600, 700],
    italic: false,
    license: "OFL-1.1",
    special: "עגול, שמח ונועז, עם עברית. מושלם לילדים, משחקים, חטיפים ומותגים צעירים.",
    designer: "",
  },
  {
    id: "bona-nova",
    family: "Bona Nova",
    cat: "serif",
    use: "שניהם",
    hebrew: true,
    weights: [400, 700],
    italic: true,
    license: "OFL-1.1",
    special: "סריף ספרותי עם נטוי ועברית. מתאים לבלוגים, הוצאות לאור ומותגים עם אופי קלאסי.",
    designer: "",
  },
  {
    id: "playpen-sans-hebrew",
    family: "Playpen Sans Hebrew",
    cat: "hand",
    use: "שניהם",
    hebrew: true,
    weights: [100, 200, 300, 400, 500, 600, 700, 800],
    italic: false,
    license: "OFL-1.1",
    special:
      "כתב יד קריא ואישי עם 8 משקלים, מה שנדיר לכתב יד. מתאים לחינוך, ילדים ומותגים אישיים, ואפשר גם לטקסט קצר.",
    designer: "TypeTogether",
  },
  {
    id: "solitreo",
    family: "Solitreo",
    cat: "hand",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "כתב הסוליטריאו ההיסטורי (כתב יד ספרדי-יהודי). לקישוט ולמיתוג ייחודי מאוד.",
    designer: "",
  },
  {
    id: "rubik-dirt",
    family: "Rubik Dirt",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "רוביק עם מרקם מלוכלך ומחוספס. לכותרות של אירועים, מוזיקה ורחוב.",
    designer: "Hubert & Fischer",
  },
  {
    id: "rubik-doodle-shadow",
    family: "Rubik Doodle Shadow",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "רוביק עם צל משורבט, שובב ומצויר. לכותרות לילדים ולמותגים קלילים.",
    designer: "Hubert & Fischer",
  },
  {
    id: "rubik-80s-fade",
    family: "Rubik 80s Fade",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "רוביק בסגנון רטרו של שנות ה-80 עם פסים. לכותרות נוסטלגיות ולמסיבות.",
    designer: "Hubert & Fischer",
  },
  {
    id: "rubik-bubbles",
    family: "Rubik Bubbles",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "רוביק מנופח כמו בועות. חמוד ומשחקי, לכותרות קצרות.",
    designer: "Hubert & Fischer",
  },
  {
    id: "rubik-wet-paint",
    family: "Rubik Wet Paint",
    cat: "display",
    use: "כותרות",
    hebrew: true,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "רוביק עם צבע נוזל. לכותרות של אירועים, ליל כל הקדושים וקמפיינים.",
    designer: "Hubert & Fischer",
  },
  {
    id: "inter",
    family: "Inter",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special: "פונט הממשקים הכי פופולרי היום. חד וקריא מאוד במסך, עם 9 משקלים ונטוי. אין בו עברית.",
    designer: "Rasmus Andersson",
  },
  {
    id: "poppins",
    family: "Poppins",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special:
      "גיאומטרי, נקי ומודרני, עם עיגולים מושלמים. נפוץ מאוד באתרי עסקים ובדפי נחיתה. אין עברית.",
    designer: "Indian Type Foundry",
  },
  {
    id: "montserrat",
    family: "Montserrat",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special: "רחב, בטוח בעצמו ואורבני. מעולה לכותרות באותיות גדולות. אין עברית.",
    designer: "Julieta Ulanovsky",
  },
  {
    id: "playfair-display",
    family: "Playfair Display",
    cat: "serif",
    use: "כותרות",
    hebrew: false,
    weights: [400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special:
      "סריף בניגודיות גבוהה, אלגנטי ומגזיני. לכותרות של מותגי יוקרה, אופנה ומסעדות. אין עברית.",
    designer: "Claus Eggers Sørensen",
  },
  {
    id: "dm-sans",
    family: "DM Sans",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special: "גיאומטרי רך ונקי, נראה מעולה בממשקים ובדפי מוצר. אין עברית.",
    designer: "Colophon Foundry",
  },
  {
    id: "manrope",
    family: "Manrope",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [200, 300, 400, 500, 600, 700, 800],
    italic: false,
    license: "OFL-1.1",
    special: "מודרני ומעט טכני, אהוב על סטארטאפים ומוצרי SaaS. אין עברית.",
    designer: "Mikhail Sharanda",
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    cat: "sans",
    use: "כותרות",
    hebrew: false,
    weights: [300, 400, 500, 600, 700],
    italic: false,
    license: "OFL-1.1",
    special: "גרוטסק עם אופי מוזר וטכנולוגי. לכותרות של מותגי טק וקריאייטיב. אין עברית.",
    designer: "Florian Karsten",
  },
  {
    id: "outfit",
    family: "Outfit",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: false,
    license: "OFL-1.1",
    special: "גיאומטרי עגול ומזמין, נראה טוב בכותרות ובכפתורים. אין עברית.",
    designer: "",
  },
  {
    id: "plus-jakarta-sans",
    family: "Plus Jakarta Sans",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [200, 300, 400, 500, 600, 700, 800],
    italic: true,
    license: "OFL-1.1",
    special: "מודרני, אלגנטי ומקצועי, מאוד פופולרי בעיצובי אתרים עכשוויים. אין עברית.",
    designer: "Tokotype",
  },
  {
    id: "sora",
    family: "Sora",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800],
    italic: false,
    license: "OFL-1.1",
    special: "טכנולוגי ורחב, מתאים לקריפטו, טק ומוצרים דיגיטליים. אין עברית.",
    designer: "",
  },
  {
    id: "fraunces",
    family: "Fraunces",
    cat: "serif",
    use: "כותרות",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special:
      'סריף רך עם אופי "עתיק-מודרני", חם ושונה. לכותרות של מותגי אוכל, קפה ובוטיק. אין עברית.',
    designer: "Undercase Type",
  },
  {
    id: "cormorant-garamond",
    family: "Cormorant Garamond",
    cat: "serif",
    use: "כותרות",
    hebrew: false,
    weights: [300, 400, 500, 600, 700],
    italic: true,
    license: "OFL-1.1",
    special: "גרמונד עדין ואלגנטי מאוד. לחתונות, תכשיטים ויוקרה. אין עברית.",
    designer: "Christian Thalmann",
  },
  {
    id: "bebas-neue",
    family: "Bebas Neue",
    cat: "display",
    use: "כותרות",
    hebrew: false,
    weights: [400],
    italic: false,
    license: "OFL-1.1",
    special: "אותיות גדולות בלבד, צר וחזק. הכותרת הקלאסית של פוסטרים וספורט. אין עברית.",
    designer: "Ryoichi Tsunekawa",
  },
  {
    id: "archivo",
    family: "Archivo",
    cat: "sans",
    use: "שניהם",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special: "גרוטסק חזק וגמיש, טוב לכותרות ולטקסט. אין עברית.",
    designer: "Omnibus-Type",
  },
  {
    id: "raleway",
    family: "Raleway",
    cat: "sans",
    use: "כותרות",
    hebrew: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: true,
    license: "OFL-1.1",
    special: "אלגנטי ודק, נראה יוקרתי בכותרות גדולות. אין עברית.",
    designer: "",
  },
  {
    id: "lora",
    family: "Lora",
    cat: "serif",
    use: "טקסט",
    hebrew: false,
    weights: [400, 500, 600, 700],
    italic: true,
    license: "OFL-1.1",
    special: "סריף נעים לקריאה עם נטוי יפה. מעולה לבלוגים ולמאמרים. אין עברית.",
    designer: "Cyreal",
  },
];

/** heading + body pairs that work */
export const PAIRS: { head: string; body: string; why: string }[] = [
  {
    head: "heebo",
    body: "frank-ruhl-libre",
    why: "מודרני עם נגיעה קלאסית: סריף לכותרות, Heebo לטקסט",
  },
  {
    head: "secular-one",
    body: "assistant",
    why: "כותרות עם אופי וטקסט שקט ונוח",
  },
  {
    head: "suez-one",
    body: "heebo",
    why: "כותרת סריף כבדה מעל טקסט נקי",
  },
  {
    head: "karantina",
    body: "rubik",
    why: "כותרות ענק צרות עם טקסט חם",
  },
  {
    head: "bellefair",
    body: "assistant",
    why: "אלגנטי ויוקרתי: אירועים, אופנה ותכשיטים",
  },
  {
    head: "fredoka",
    body: "varela-round",
    why: "שמח ועגול: ילדים וחינוך",
  },
  {
    head: "frank-ruhl-libre",
    body: "noto-serif-hebrew",
    why: "קלאסי לגמרי: מוסדות ותוכן תורני",
  },
  {
    head: "playfair-display",
    body: "inter",
    why: "יוקרה באנגלית: כותרת מגזינית וטקסט חד",
  },
  {
    head: "bebas-neue",
    body: "montserrat",
    why: "פוסטר וספורט באנגלית",
  },
  {
    head: "fraunces",
    body: "dm-sans",
    why: "בוטיק, אוכל וקפה באנגלית",
  },
  {
    head: "space-grotesk",
    body: "inter",
    why: "טק וסטארטאפים באנגלית",
  },
  {
    head: "cormorant-garamond",
    body: "manrope",
    why: "חתונות ויוקרה באנגלית",
  },
];
