/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBriefRouteImport } from './routes/api/brief'
import { Route as ApiSiteCheckRouteImport } from './routes/api/site-check'
import { Route as ApiSiteMonitorRouteImport } from './routes/api/site-monitor'
import { Route as BIdRouteImport } from './routes/b.$id'
import { Route as ApiGrowWebhookRouteImport } from './routes/api/grow/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteCheckRoute = ApiSiteCheckRouteImport.update({
  id: '/api/site-check',
  path: '/api/site-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteMonitorRoute = ApiSiteMonitorRouteImport.update({
  id: '/api/site-monitor',
  path: '/api/site-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const BIdRoute = BIdRouteImport.update({
  id: '/b/$id',
  path: '/b/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrowWebhookRoute = ApiGrowWebhookRouteImport.update({
  id: '/api/grow/webhook',
  path: '/api/grow/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/site-check': typeof ApiSiteCheckRoute
  '/api/site-monitor': typeof ApiSiteMonitorRoute
  '/b/$id': typeof BIdRoute
  '/api/grow/webhook': typeof ApiGrowWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/site-check': typeof ApiSiteCheckRoute
  '/api/site-monitor': typeof ApiSiteMonitorRoute
  '/b/$id': typeof BIdRoute
  '/api/grow/webhook': typeof ApiGrowWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/site-check': typeof ApiSiteCheckRoute
  '/api/site-monitor': typeof ApiSiteMonitorRoute
  '/b/$id': typeof BIdRoute
  '/api/grow/webhook': typeof ApiGrowWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/brief'
    | '/api/site-check'
    | '/api/site-monitor'
    | '/b/$id'
    | '/api/grow/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/brief'
    | '/api/site-check'
    | '/api/site-monitor'
    | '/b/$id'
    | '/api/grow/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/brief'
    | '/api/site-check'
    | '/api/site-monitor'
    | '/b/$id'
    | '/api/grow/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiSiteCheckRoute: typeof ApiSiteCheckRoute
  ApiSiteMonitorRoute: typeof ApiSiteMonitorRoute
  BIdRoute: typeof BIdRoute
  ApiGrowWebhookRoute: typeof ApiGrowWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-check': {
      id: '/api/site-check'
      path: '/api/site-check'
      fullPath: '/api/site-check'
      preLoaderRoute: typeof ApiSiteCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-monitor': {
      id: '/api/site-monitor'
      path: '/api/site-monitor'
      fullPath: '/api/site-monitor'
      preLoaderRoute: typeof ApiSiteMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$id': {
      id: '/b/$id'
      path: '/b/$id'
      fullPath: '/b/$id'
      preLoaderRoute: typeof BIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grow/webhook': {
      id: '/api/grow/webhook'
      path: '/api/grow/webhook'
      fullPath: '/api/grow/webhook'
      preLoaderRoute: typeof ApiGrowWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiSiteCheckRoute: ApiSiteCheckRoute,
  ApiSiteMonitorRoute: ApiSiteMonitorRoute,
  BIdRoute: BIdRoute,
  ApiGrowWebhookRoute: ApiGrowWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
